apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- openshift-storage-namespace.yaml
- openshift-storage-operatorgroup.yaml
- lvms-operator-subscription.yaml
- lvms-catalogsource.yaml

# image configurations
configurations:
- lvms-catalogsource-image.yaml

# replace catalogsource image
images:
- name: catalog-img
  newName: quay.io/ocs-dev/lvms-operator-catalog
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/channel
      value: alpha
  target:
    kind: Subscription
    name: lvms-operator
