apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: lvms-catalogsource
  namespace: openshift-storage
spec:
  sourceType: grpc
  image: catalog-img
  displayName: Red Hat, Inc
  publisher: Red Hat
