---
name: golangci-lint

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
env:
  GO_VERSION: "1.18"

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or
          # v1.2.3 or `latest` to use the latest version
          version: v1.45.2

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # TODO: remove --skip-files once logic is implemented
          args: >
            -E gosec --timeout=6m --skip-files
            controllers/suite_test.go,api/v1alpha1/webhook_suite_test.go

          # Optional: show only new issues if it's a pull request.
          # The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          skip-go-installation: true

          # Optional: if set to true then the action don't cache or
          # restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or
          # restore ~/.cache/go-build.
          # skip-build-cache: true
